job:
  script: entrypoint.sh

pvc:
  # Leave empty to use the default storage class
  storageClass: ""

  accessMode: ReadWriteOnce
  
  # Size of the storage needed to hold the database dump
  size: 1Gi