apiVersion: "batch/v1"
kind: "Job"
metadata:
  name: {{ printf "%s-%s" .Release.Namespace "job" | quote }}
  labels:
    app: {{ printf "%s-%s" .Release.Namespace "netbox-migration" | quote }}
    housekeeping: {{ include "migration.housekeeping" . | quote }}
  annotations:
    "helm.sh/hook": "post-install"
    "helm.sh/hook-weight": "10"
spec:
  selector: {}
  template:
    metadata:
      name: "fetch-data"
    spec:
      serviceAccountName: {{ printf "%s-%s" .Release.Namespace "serviceaccount" | quote }}
      restartPolicy: OnFailure
      containers:
        - name: "fetch-data"
          image: "image-registry.openshift-image-registry.svc:5000/netbox-migration/netbox-migration:latest"
          imagePullPolicy: "Always"
          command:
            - 'bin/sh'
            - '-c'
            - '/migration/configmap/entrypoint.sh'
          volumeMounts:
            - name: "migration-data"
              mountPath: "/migration/data/"
          resources:
            limits:
              memory: "500Mi"
              cpu: "500m"
      volumes:
        - name: "migration-data"
          persistentVolumeClaim:
            claimName: "netbox-migration"