kind: "RoleBinding"
apiVersion: "rbac.authorization.k8s.io/v1"
metadata:
  name: {{ printf "%s-%s" .Release.Namespace "image-puller" | quote }}
  namespace: "netbox-migration"
  labels:
    app: {{ printf "%s-%s" .Release.Namespace "netbox-migration" | quote }}
    housekeeping: {{ include "migration.housekeeping" . | quote }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "-10"
subjects:
  - kind: "ServiceAccount"
    name: {{ printf "%s-%s" .Release.Namespace "serviceaccount" | quote }}
    namespace: {{ .Release.Namespace | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: "ClusterRole"
  name: "system:image-puller"
