apiVersion: "v1"
kind: "ServiceAccount"
metadata:
  name: {{ printf "%s-%s" .Release.Namespace "serviceaccount" | quote }}
  labels:
    app: {{ printf "%s-%s" .Release.Namespace "netbox-migration" | quote }}
    housekeeping: {{ include "migration.housekeeping" . | quote }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "-10"