apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: {{ include "netbox.fullname" . }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "netbox.labels" . | nindent 4 }}
    app.kubernetes.io/component: netbox
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.deploymentConfig.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "netbox.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: netbox
  {{ if .Values.deploymentConfig.updateStrategy -}}
  strategy:
    {{- toYaml .Values.deploymentConfig.updateStrategy | nindent 4 }}
  {{ end -}}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- if (not .Values.existingSecret) }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- end }}
        {{- with .Values.deploymentConfig.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "netbox.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: netbox
        {{- with .Values.deploymentConfig.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.image.imagePullSecrets }}
      image.imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "netbox.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.deploymentConfig.podSecurityContext | nindent 8 }}
      initContainers:
        - name: init-dirs
          image: "{{ .Values.initContainers.image.repository }}:{{ .Values.initContainers.image.tag }}"
          imagePullPolicy: {{ .Values.deploymentConfig.initContainers.image.pullPolicy }}
          command: [/bin/sh, -c, mkdir -p /opt/unit/state /opt/unit/tmp]
          {{- if .Values.deploymentConfig.initContainers.resources }}
          resources:
            {{- toYaml .Values.deploymentConfig.initContainers.resources | nindent 12 }}
          {{- end }}
          securityContext:
            {{- toYaml .Values.deploymentConfig.initContainers.securityContext | nindent 12 }}
          volumeMounts:
            - name: optunit
              mountPath: /opt/unit
        {{- with .Values.deploymentConfig.initContainers.extraInitContainers }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.deploymentConfig.containers.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: SUPERUSER_NAME
              value: {{ .Values.superuser.name | quote }}
            - name: SUPERUSER_EMAIL
              value: {{ .Values.superuser.email | quote }}
            - name: SKIP_STARTUP_SCRIPTS
              value: {{ .Values.deploymentConfig.containers.skipStartupScripts | quote }}
            {{- if .Values.deploymentConfig.containers.dbWaitDebug }}
            - name: DB_WAIT_DEBUG
              value: "1"
            {{- end }}
            {{- with .Values.deploymentConfig.containers.extraEnvs }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          {{- if .Values.deploymentConfig.containers.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: /{{ .Values.basePath }}login/
              port: http
              {{- if (not (eq (index .Values.allowedHosts 0) "*")) }}
              httpHeaders:
                - name: Host
                  value: {{ (index .Values.allowedHosts 0) | quote }}
              {{- end }}
            initialDelaySeconds: {{ .Values.deploymentConfig.containers.readinessProbe.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.deploymentConfig.containers.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.deploymentConfig.containers.readinessProbe.successThreshold }}
            periodSeconds: {{ .Values.deploymentConfig.containers.readinessProbe.periodSeconds }}
          {{- end }}
          volumeMounts:
            - name: config
              mountPath: /etc/netbox/config/configuration.py
              subPath: configuration.py
              readOnly: true
            {{ if eq .Values.remoteAuthBackend "netbox.authentication.LDAPBackend" -}}
            - name: config
              mountPath: /etc/netbox/config/ldap/ldap_config.py
              subPath: ldap_config.py
              readOnly: true
            {{ end -}}
            - name: config
              mountPath: /run/config/netbox
              readOnly: true
            - name: secrets
              mountPath: /run/secrets/netbox
              readOnly: true
            {{- include "netbox.extraConfig.volumeMounts" . | nindent 12 -}}
            - name: netbox-tmp
              mountPath: /tmp
            - name: media
              mountPath: /opt/netbox/netbox/media
              subPath: {{ .Values.persistence.subPath | default "" | quote }}
            {{- if .Values.reportsPersistence.enabled }}
            - name: reports
              mountPath: /opt/netbox/netbox/reports
              subPath: {{ .Values.reportsPersistence.subPath | default "" | quote }}
            {{- end }}
            - name: optunit
              mountPath: /opt/unit
            - name: secrets
              mountPath: /run/secrets/superuser_password
              subPath: superuser_password
              readOnly: true
            - name: secrets
              mountPath: /run/secrets/superuser_api_token
              subPath: superuser_api_token
              readOnly: true
            {{- with .Values.deploymentConfig.containers.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- if .Values.deploymentConfig.containers.resources }}
          resources:
            {{- toYaml .Values.deploymentConfig.containers.resources | nindent 12 }}
          {{- end }}
        {{- with .Values.deploymentConfig.containers.extraContainers }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "netbox.fullname" . }}
        - name: secrets
          projected:
            sources:
              - secret:
                  name: {{ .Values.existingSecret | default (include "netbox.fullname" .) | quote }}
                  items:
                    # Used by netbox-docker entry scripts
                    - key: superuser_password
                      path: superuser_password
                    - key: superuser_api_token
                      path: superuser_api_token
                    # Used by our configuration
                    - key: email_password
                      path: email_password
                    - key: napalm_password
                      path: napalm_password
                    - key: secret_key
                      path: secret_key
                    {{- if eq .Values.remoteAuthBackend "netbox.authentication.LDAPBackend" }}
                    - key: ldap_bind_password
                      path: ldap_bind_password
                    {{- end }}
              - secret:
                  name: {{ include "netbox.postgresql.secret" . | quote }}
                  items:
                    - key: {{ include "netbox.postgresql.secretKey" . | quote }}
                      path: db_password
              - secret:
                  name: {{ include "netbox.tasksRedis.secret" . | quote }}
                  items:
                    - key: {{ include "netbox.tasksRedis.secretKey" . | quote }}
                      path: redis_tasks_password
              - secret:
                  name: {{ include "netbox.cachingRedis.secret" . | quote }}
                  items:
                    - key: {{ include "netbox.cachingRedis.secretKey" . | quote }}
                      path: redis_cache_password
        {{- include "netbox.extraConfig.volumes" . | nindent 8 -}}
        - name: netbox-tmp
          emptyDir:
            medium: Memory
        - name: optunit
          emptyDir:
            medium: Memory
        - name: media
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (printf "%s-media" (include "netbox.fullname" .)) }}
          {{- else }}
          emptyDir: {}
          {{- end }}
        {{- if .Values.reportsPersistence.enabled }}
        - name: reports
          persistentVolumeClaim:
            claimName: {{ .Values.reportsPersistence.existingClaim | default (printf "%s-reports" (include "netbox.fullname" .)) }}
        {{- end }}
        {{- with .Values.deploymentConfig.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.deploymentConfig.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deploymentConfig.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deploymentConfig.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deploymentConfig.hostAliases }}
      hostAliases:
        {{- toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.deploymentConfig.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
