{{- if and .Values.useMigration .Values.useBundlePostgresql -}}
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: netbox-migration-imagestream
  {{- with .Values.commonAnnotations }}
  annotations:
    openshift.io/display-name: netbox-migration-imagestream
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "netbox.labels" . | nindent 4 }}
spec:
  lookupPolicy:
    local: true
{{- end -}}