{{- if and .Values.persistence.reports.enabled (not .Values.persistence.reports.existingClaim) -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "netbox.fullname" . }}-reports
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
{{ include "netbox.labels" . | indent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.reports.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.reports.size | quote }}
{{- if .Values.persistence.reports.storageClass }}
{{- if (eq "-" .Values.persistence.reports.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: {{ .Values.persistence.reports.storageClass | quote }}
{{- end }}
{{- end }}
{{- if .Values.persistence.reports.selector }}
  selector: {{ toYaml .Values.persistence.reports.selector | nindent 4 }}
{{- end }}
{{- end -}}
