{{- if and .Values.useNetboxWorker .Values.workerAutoscaling.enabled }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "netbox.fullname" . }}-worker
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "netbox.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "netbox.fullname" . }}-worker
  minReplicas: {{ .Values.workerAutoscaling.minReplicas }}
  maxReplicas: {{ .Values.workerAutoscaling.maxReplicas }}
  metrics:
  {{- if .Values.workerAutoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ .Values.workerAutoscaling.targetCPUUtilizationPercentage }}
  {{- end }}
  {{- if .Values.workerAutoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: {{ .Values.workerAutoscaling.targetMemoryUtilizationPercentage }}
  {{- end }}
{{- end }}
